### ISSUE TITLE
Supports for Spans on parsing

### ISSUE THREAD

**Issue by Trojaner** [jamescourtney/FlatSharp#16]
The problem with parsing is that it relies on InputBuffer class.
This would need something like this for reading Spans.

```cs
public class SpanInputBuffer : InputBuffer
{
    private Span<byte> _span;
    public SpanInputBuffer(Span<byte> span) 
    {
       _span = span;
    }
   
    public override byte ReadByte(int offset) => _span[offset];
    [...]
}
```

However as we all know spans are stack-only, so they can not be field members.
A possible solution would be to read from buffers with unsafe code instead (e.g. from `IntPtr` or `byte*`).
Kudos to @nxrighthere for the fix suggestion.

**Comment by jamescourtney** [comment]
Hi there --

I'm really sorry for my delay on this. Life happened over the winter, and I'm just catching up.

Anyway, yeah, I struggled with this a lot, and my conclusion was the same as yours: since spans can't be field members, then it's simply not possible to keep them around and do lazy deserialization, which is the whole point. That's explicitly what Memory is for. The downside of memory is that the "safe" version is kind of slow because the .Span property has some slowness because the Memory needs to be pinned.

The UnsafeMemoryInputBuffer class actually performs as you'd hope (and largely works as you describe), but it requires disposal since it pins the memory in place so that accesses are faster. That said, you're under no obligation to dispose if you think the finalizer can deal with it.

The fastest, safest thing is *probably* just doing memory.ToArray() and using ArrayInputBuffer.

**Comment by Trojaner** [comment]
Thank you, I will consider using your suggestions!
