### ISSUE TITLE
Comparsion of data size

### ISSUE THREAD

**Issue by nxrighthere** [jamescourtney/FlatSharp#2]
James, thanks for this implementation. I like the fact that it's based on `Memory<T>` and `Span<T>`, this is something fresh for me in the serializers area.

Can you please provide data size comparison with those serialization libraries in the readme?

**Comment by jamescourtney** [comment]
This is a good idea, and I'll look at it soon. Still busy trying to get the core of FlatSharp done in a way that I'm happy with and that I can stand behind.

In general, FlatBuffers will be chattier than, say, Protobuf, since it uses fixed-width encodings and writes only aligned data. For big bytes arrays or big strings, there won't be a huge difference. I've just published alpha-ish packages under "FlatSharp" and "FlatSharp.Unsafe" that you can play with if you like. Would love to know your thoughts!
