### ISSUE TITLE
FlatSharp.Compiler .net standard 2

### ISSUE THREAD

**Issue by JurjenBiewenga** [jamescourtney/FlatSharp#249]
Hi,

We're using a shared library between one of our server applications and our Unity project that contains our schemas and some helpers. This is working perfectly fine however we're stuck on .net standard 2 as our Unity version does not support any higher currently. Is there any chance of getting .net standard 2 support back in the compiler nuget or should we manually call the flatsharp compiler as a build process step?

Thanks

**Comment by jamescourtney** [comment]
The FlatSharp compiler is a standalone executable. I ship both `net5.0` and `netcoreapp3.1` versions of the compiler. The `FlatSharp.Runtime` package does support `netstandard2.0`, which should work for you. All you'll need to make sure of is that your build environment has either .NET Core 3.1 or .NET 5 installed, and you should be able to use the FlatSharp compiler as a command line tool.

Those who use Unity with FlatSharp usually do so by invoking the FlatSharp compiler as a prebuild step, since Unity does not allow editing .csproj files. You can find documentation about the compiler [here](https://github.com/jamescourtney/FlatSharp/wiki/Compiler).

(As an aside, .NET Standard can be thought of as headers, where as .NET Framework and .NET Core are the implementations. For this reason, you can't actually ship a .NET Standard executable, because it's an API without implementation. You can, however, produce .NET Standard DLLs that will work correctly in any runtime that supports that version of .NET Standard.)

**Comment by JurjenBiewenga** [comment]
Our shared library is a separate C# project (gets copied to unity with required dependencies after build), and thus we use the nuget packages there. 

Somewhere in the 5.x to 6.x cycle, support on the NuGet package for net standard 2 was dropped. Taking a quick look at the compiler project, seems like adding net standard 2 as a target doesn't cause any problems. Of course, you'll know better if it's possible.

Ideally we'll want to keep using the NuGet package as it doesn't make our build pipeline any more complex but if that's really not possible then I'll look into invoking the compiler manually.

**Comment by jamescourtney** [comment]
What got dropped in version 6 was `netcoreapp2.0`, which went out of support in August. The compiler has never targeted .NET Standard.

**Comment by JurjenBiewenga** [comment]
Oh sorry! I somehow read those as the same (although I know the difference). My point is still the same, FlatSharp.Compiler can still produce a netstandard 2 compatible binary.

**Comment by jamescourtney** [comment]
Is this what you're seeing? 

![image](https://user-images.githubusercontent.com/2636896/144987410-f5dbc50e-fd3c-4d99-b0a4-e84268872ba1.png)

If so, that's obnoxious since the compiler is just a tool package. I'm actually more surprised it worked before in version 5. I'll see what I can do to get 6.0.2 published in the next 24 hours or so.

**Comment by jamescourtney** [comment]
It's bedtime for me, but I'll look at this tomorrow.

**Comment by JurjenBiewenga** [comment]
Yeah, perhaps I should've been a bit more clear. Thanks, I really appreciate it! There's no hurry, already postponed updating for a few weeks.

**Comment by jamescourtney** [comment]
#250 tracks the progress of me trial-and-erroring my way to fixing this

**Comment by jamescourtney** [comment]
This is fixed in 6.0.2, which was just published to NuGet. The full release notes for v6 are [here](https://github.com/jamescourtney/FlatSharp/releases/tag/6.0.0). Keep in mind that there are some breaking changes in V6, so I really encourage you to read the full release notes. Thanks for using FlatSharp! Please let me know how Version 6 works for you when you do end up upgrading.

**Comment by JurjenBiewenga** [comment]
Seems to work perfect now! We were already mostly compatible with Flatc (we've got third parties consuming our schemas). Thanks a lot!
