### ISSUE TITLE
[Bug] Using the latest "Standalone" `FlatSharp` nuget in a .net6 project; generates a file that requires `IPoolableObject`

### ISSUE THREAD

**Issue by Smurf-IV** [jamescourtney/FlatSharp#382]
But `IPoolableObject` is missing:

![image](https://github.com/jamescourtney/FlatSharp/assets/2418812/6111b73e-ab8c-4235-a01c-f3d33eb764fa)

Along with lot's of other unrelated to code errors; e,g,
1>#######V23CliCs\FlatSharp.generated.cs(736,22,736,37): error CS0246: The type or namespace name 'BuildSerializer' could not be found (are you missing a using directive or an assembly reference?)

**Comment by Smurf-IV** [comment]
Note:
If the nuget is changed to the folowing
`    <PackageReference Include="FlatSharp.Runtime" Version="7.1.0" />`
Then it works as expected.
I think the "Standalone" `FlatSharp` nuget should be deprecated if IP{oolAble etc are not going to be added to it.

**Comment by jamescourtney** [comment]
Hello -- apologies for my delayed response. You can see the [release notes](https://github.com/jamescourtney/FlatSharp/releases/tag/7.0.0) for the rationale on why I deprecated the `FlatSharp` package. I didn't mark it as deprecated initially because v7 has been out only for a year, and I didn't want to cause breaks for people still depending on it. I'll take an action to see what I can do to mark that package as deprecated in NuGet.
