### ISSUE TITLE
Don't use Nullable properties for GreedyMutable only serializers

### ISSUE THREAD

**Issue by duckdoom4** [jamescourtney/FlatSharp#401]
I do have one more question though. If we have `GreedyMutable` as the only deserializer option, doesn't that automatically mean that non of the properties should be marked as nullable?

I'd rather not have to mark every single property as (required)
![image](https://github.com/jamescourtney/FlatSharp/assets/60387522/2c25d12a-7a62-4156-a5e2-f485c8f94026)

**Comment by duckdoom4** [comment]
As a workaround I can just set `<FlatSharpNullable>false</FlatSharpNullable>` on all projects I guess

**Comment by jamescourtney** [comment]
So, even with GreedyyMutable, FlatBuffers supports the concept of `null`, which is why FlatSharp emits the annotation. If you want to encode this assertion, consider marking properties as `required`. This will cause FlatSharp to throw when parsing if it encounters a `null` property that should be there.

**Comment by duckdoom4** [comment]
It's been a while since I've read the file format's documentation and it might also be that the specific implementation that is used in our case might handle this differently so correct me if i'm wrong; but doesn't it just assign it as 'default' if it's 'null' meaning most things can't actually be null

**Comment by duckdoom4** [comment]
Oh but that's actually already happening here, you only assign nullable to objects and lists. I see
