### ISSUE TITLE
The type initializer for 'FlatSharp.RoslynSerializerGenerator' threw an exception

### ISSUE THREAD

**Issue by PeterFuzz** [jamescourtney/FlatSharp#72]
Howdy,

This is probably a total noob question, but I'm not able to get a serializer instantiated:

```
            Upstream up = new Upstream();
            up.Structure = new FSeed();
            up.Structure.Data = new ConfigEntry[1];
            var e0 = new ConfigEntry();
            up.Structure.Data[0] = e0;
            e0.Tag = "stuff";
            e0.Type = "string";
            e0.Used = true;
            
            Console.WriteLine("test serializing up");
            
            var testBuffer = new byte[1000];
            
            var serializer = new FlatBufferSerializer(new FlatBufferSerializerOptions(FlatBufferDeserializationOption.Default));
            
            var testLength = serializer.Serialize(up, testBuffer);
            
            Upstream up2 = serializer.Parse<Upstream>(testBuffer);
```

I keep on getting this exception:
```
System.TypeInitializationException: The type initializer for 'FlatSharp.RoslynSerializerGenerator' threw an exception. ---> System.IO.FileNotFoundException: The system cannot find the file specified. (Exception from HRESULT: 0x80070002)
   at System.Reflection.RuntimeAssembly.nLoadFile(String path, Evidence evidence)
   at System.Reflection.Assembly.LoadFile(String path)
   at FlatSharp.RoslynSerializerGenerator..cctor()
   --- End of inner exception stack trace ---
   at FlatSharp.RoslynSerializerGenerator..ctor(FlatBufferSerializerOptions options, TypeModelContainer typeModelContainer)
   at FlatSharp.FlatBufferSerializer.GetOrCreateSerializer[TRoot]()
   at FlatSharp.FlatBufferSerializer.Serialize[T,TSpanWriter](T item, Span`1 destination, TSpanWriter writer)
   at FlatSharp.FlatBufferSerializer.Serialize[T](T item, Span`1 destination)
   at LibToFuzz.FuzzMe.Main(String[] args) in C:\Users\PeterFuzz\go\src\github.com\fuzzbuzz\platform\sfz\sfz-build-csharp\LibToFuzz\LibToFuzz\Program.cs:line 104
```

I'm bewildered. Nothing inside the exception object resembles a filename.

**Comment by jamescourtney** [comment]
Hi Peter -- thank you for reaching out. This block of code has been problematic in the past, unfortunately.

What's happening is that at runtime, FlatSharp is going to create a bunch of C# and build a DLL for you, then load it, then invoke it. But to build the DLL, it has to know the locations of the other assemblies that it needs to reference, which can vary from machine to machine and runtime to runtime, (hence the "problematic") part. In this case, it's not finding one of those and is bombing out with this obscure error. The usual one is "netstandard.dll". The code for this special bit of logic is here: https://github.com/jamescourtney/FlatSharp/blob/e416b0ea236d808e9e980415c7fc12033de6d2f6/src/FlatSharp/Serialization/RoslynSerializerGenerator.cs#L58

Whether this is expected or not depends on the runtime environment. It's only supposed to work on .NET Framework 4.7+ or .NET Core 2.1+. If this is the case, can you share the details of what .NET version you're targeting and what runtime you're using? Or even better provide a small sample that reproduces the issue? I'd love to get this fixed.

On the other hand, if you're on Mono, Unity, Xamarin, etc, you'll have a much better time using the FlatSharp.Compiler package and generating your code at build-time instead of runtime. The Compiler package will work fine as long as you have .NET Core 2.1 installed (you don't need to be targeting that framework -- the compiler itself  is built for that version).

**Comment by PeterFuzz** [comment]
I've created a sample github repo here:
https://github.com/StCredZero/TryFlatSharp

Using the Rider IDE, build-Debug gets us the exception. (enclosed)
![image](https://user-images.githubusercontent.com/54908986/95639860-f0e1f880-0a4e-11eb-8329-1b51eda06247.png)

**Comment by jamescourtney** [comment]
I couldn't get your solution to build, but I was able to reproduce this issue by targeting the FlatSharp unit tests at .NET Framework 4.7.2

To fix it, I added the following to my .csproj file:

```
  <ItemGroup>
    <Reference Include="netstandard">
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Collections">
      <Private>true</Private>
    </Reference>
    <Reference Include="System.Runtime">
      <Private>true</Private>
    </Reference>
  </ItemGroup>
```

I'll need to investigate some more to see how practical it is to fold these references into some sort of targets file that can ship with FlatSharp, but this should unblock you for now.

**Comment by jamescourtney** [comment]
This should be addressed by #73 . I'll likely have it published later today.

**Comment by jamescourtney** [comment]
Version 4.0.2 has been published to nuget. It should resolve this issue without any need for you to manually include any references. Feel free to reactivate this issue if you still experience problems. Thanks for giving FlatSharp a try!

**Comment by PeterFuzz** [comment]
Thanks for getting back to me so quick! I'll give this a try.
